export enum Category {
  DESIGN = "DESIGN",
  INTERFACE = "INTERFACE",
  ENGINEERING = "ENGINEERING",
  MARKETING = "MARKETING",
}

export enum Plan {
  INDIVIDUAL = "INDIVIDUAL",
  PROFESSIONAL = "PROFESSIONAL",
  ENTERPRISE = "ENTERPRISE",
}
